# jshint last release was 2 years ago, and hang locally
jshint:
  config_file: .jshintrc
# ESLint supported version
# http://help.houndci.com/en/articles/2461415-supported-linters
eslint:
  enabled: true
  version: 8.1.0
  config_file: .hound_eslint_config.json