# create bot action trigger
name: BES_trigger_healthcheck_action
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: github_actions_bes
    steps:
      - name: trigger botEnSky healthcheck ACTION
        env:
          BES_ACTION_TOKEN: ${{ secrets.BES_ACTION_TOKEN }}
          BES_ACTION_URL: ${{ secrets.BES_ACTION_URL }}
        run: |
          curl -q -H "API-TOKEN: ${BES_ACTION_TOKEN}" -H "PLUGIN-NAME: HealthCheck" "${BES_ACTION_URL}"
