# create bot action trigger
name: BES_trigger_1day1bioclip_action
on:
  # cf. readme
  schedule: # 12h10 (FR timezone)
    # (CET) Standard time (UTC+1)
    - cron: '10 11 * 11-12,1-3 *'
    # (CET) Daylight saving time (UTC+2)
    - cron: '10 10 * 4-10 *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: github_actions_bes
    steps:
      - name: trigger botEnSky 1Day1Bioclip ACTION
        env:
          BES_ACTION_TOKEN: ${{ secrets.BES_ACTION_TOKEN }}
          BES_ACTION_URL: ${{ secrets.BES_ACTION_URL }}
        run: |
          curl -q -H "API-TOKEN: ${BES_ACTION_TOKEN}" -H "PLUGIN-NAME: OneDayOneBioclip" "${BES_ACTION_URL}"
