# create bot action trigger
name: BES_trigger_askbioclip_action
on:
  # cf. readme
  schedule: # 09h00, 12h00, 15h00, 17h00, 18h00 et 21h00 (FR timezone)
    # (CET) Standard time (UTC+1)
    - cron: '00 8,11,14,16,17,20 * 11-12,1-3 *'
    # (CET) Daylight saving time (UTC+2)
    - cron: '00 7,10,13,15,16,19 * 4-10 *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: github_actions_bes
    steps:
      - name: trigger botEnSky AskBioclip ACTION
        env:
          BES_ACTION_TOKEN: ${{ secrets.BES_ACTION_TOKEN }}
          BES_ACTION_URL: ${{ secrets.BES_ACTION_URL }}
        run: |
          curl -q -H "API-TOKEN: ${BES_ACTION_TOKEN}" -H "PLUGIN-NAME: AskBioclip" "${BES_ACTION_URL}"
