# create bot action trigger
name: BES_trigger_bioclip_action
on:
  # cf. readme
  schedule: # 08h50, 11h50, 14h50, 16h50, 17h50 et 20h50 (FR timezone)
    # (CET) Standard time (UTC+1)
    - cron: '50 7,10,13,15,16,19 * 11-12,1-3 *'
    # (CET) Daylight saving time (UTC+2)
    - cron: '50 6,9,12,14,15,18 * 4-10 *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: github_actions_bes
    steps:
      - name: trigger botEnSky Bioclip ACTION
        env:
          BES_ACTION_TOKEN: ${{ secrets.BES_ACTION_TOKEN }}
          BES_ACTION_URL: ${{ secrets.BES_ACTION_URL }}
        run: |
          curl -q -H "API-TOKEN: ${BES_ACTION_TOKEN}" -H "PLUGIN-NAME: BioClip" "${BES_ACTION_URL}"
